name: docker-tag

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.event.pull_request }}
          echo ${{ github.event_name }}
