name: docker-tag

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo pr: ${{ github.event.pull_request }}
          echo pr.merged: ${{ github.event.pull_request.merged }}
          echo pr.comment: ${{ github.event.pull_request.comment }}
          echo pr.pr.comments: ${{ github.event.pull_request.pull_request.comments }}
          echo pr.pr.issue: ${{ github.event.pull_request.pull_request.issue }}
          echo ev: ${{ github.event }}
          echo ev.push: ${{ github.event.push }}
          echo ev_na: ${{ github.event_name }}

      - name: script
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body;
            const lines = body.split('\n').map((l)=>l.trim();
            const closes = new RegExp(
              /(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)/)
            console.log(1);
            console.log(body);
            console.log(2);
            console.log(lines);
            console.log(3);
            console.log(lines.filter((l)=>l.match(closes));
            console.log(4);
            console.log(context.payload);
