name: docker-tag

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.event.pull_request }}
          echo ${{ github.event }}
          echo ${{ github.event.push }}
          echo ${{ github.event_name }}
